<template>
  <div class="overview-page"><AppHeader /><main class="overview-main">
    <div class="overview-topline"><span><span class="signal-dot" />NEXUS / WORKSPACE</span><time>{{ today }}</time></div>
    <section class="overview-hero">
      <div class="hero-grid" aria-hidden="true" /><div class="hero-copy"><span class="hero-kicker">KNOWLEDGE × CONNECTION</span><h1>智能的下一次跃迁，<br /><em>从互联开始。</em></h1><p>发现值得复用的 Skill，连接实用的 MCP。<br />在这里，把工具、知识和协作放在一起。</p><div class="hero-actions"><RouterLink to="/skills" class="btn btn-primary"><Blocks :size="16" />探索 Skill<ArrowUpRight :size="15" /></RouterLink><RouterLink to="/mcp-servers" class="btn btn-secondary"><Plug :size="16" />连接 MCP</RouterLink></div></div>
      <div class="network-art" aria-hidden="true"><div class="orbit orbit-one" /><div class="orbit orbit-two" /><div class="orbit orbit-three" /><div class="core-node"><Network :size="40" /><strong>NEXUS</strong></div><div class="satellite satellite-a"><Blocks :size="22" /><span>SKILL</span></div><div class="satellite satellite-b"><Plug :size="22" /><span>MCP</span></div><div class="satellite satellite-c"><Handshake :size="20" /></div><span class="art-caption">IDEAS BECOME POSSIBILITIES</span></div>
    </section>
    <section class="overview-stats" aria-label="资源统计"><RouterLink to="/skills"><Blocks :size="19" /><span>已收录 Skill<small>可复用的方法与能力</small></span><strong>{{ skillTotal ?? '—' }}</strong><ArrowUpRight :size="14" /></RouterLink><RouterLink to="/mcp-servers"><Plug :size="19" /><span>已收录 MCP<small>连接外部工具与数据</small></span><strong>{{ mcpTotal ?? '—' }}</strong><ArrowUpRight :size="14" /></RouterLink><RouterLink to="/help-requests"><CircleHelp :size="19" /><span>从一个问题开始<small>发布需求，找到同行者</small></span><ArrowUpRight :size="17" /></RouterLink></section>
    <section class="discovery-section"><header class="section-heading"><div><span class="section-index">01 / DISCOVER</span><h2>发现新的可能</h2></div><div class="discovery-tabs"><button :class="{active: selectedKind === 'skill'}" :aria-pressed="selectedKind === 'skill'" @click="selectedKind = 'skill'">Skill</button><button :class="{active: selectedKind === 'mcp'}" :aria-pressed="selectedKind === 'mcp'" @click="selectedKind = 'mcp'">MCP</button></div><RouterLink :to="selectedKind === 'skill' ? '/skills' : '/mcp-servers'">浏览全部<ArrowUpRight :size="14" /></RouterLink></header><StatePanel v-if="loading" tone="loading" title="正在探索资源" /><StatePanel v-else-if="error" tone="error" title="资源暂时无法加载" :description="error"><button class="btn btn-secondary" @click="load">重新加载</button></StatePanel><div v-else-if="visibleResources.length" class="resource-grid"><ResourceCard v-for="resource in visibleResources" :key="resource.id" :resource="resource" compact @open="openResource" /></div><StatePanel v-else title="等待第一个好工具" description="收录一个值得推荐的资源，让更多人发现它。"><RouterLink :to="selectedKind === 'skill' ? '/skills' : '/mcp-servers'" class="btn btn-secondary">开始收录<ArrowUpRight :size="15" /></RouterLink></StatePanel></section>
    <section class="community-section"><header class="section-heading"><div><span class="section-index">02 / COLLABORATE</span><h2>与人连接，一起推进</h2></div></header><div class="community-entry-grid"><RouterLink v-for="entry in communityEntries" :key="entry.to" :to="entry.to" class="community-entry"><span class="entry-icon"><component :is="entry.icon" :size="23" /></span><div><h3>{{ entry.title }}</h3><p>{{ entry.description }}</p></div><ArrowUpRight :size="17" /></RouterLink></div></section>
    <footer class="overview-footer"><span>NEXUS · CONNECTED POSSIBILITIES</span><RouterLink to="/docs">第一次使用？从这里开始<ArrowUpRight :size="13" /></RouterLink></footer>
  </main></div>
</template>
<script setup lang="ts">
import { computed, onBeforeUnmount, ref } from 'vue'
import { RouterLink, useRouter } from 'vue-router'
import { ArrowUpRight, Blocks, CircleHelp, Handshake, MessagesSquare, Network, Plug } from '@lucide/vue'
import AppHeader from '@/components/AppHeader.vue'
import StatePanel from '@/components/StatePanel.vue'
import ResourceCard from '@/features/resources/ResourceCard.vue'
import { listResources, errorMessage, type Resource } from '@/features/resources/api'
import '@/features/resources/resources.css'
const router = useRouter()
const today = new Date().toLocaleDateString('zh-CN', {year:'numeric',month:'2-digit',day:'2-digit'})
const skillTotal = ref<number>(); const mcpTotal = ref<number>()
const skills = ref<Resource[]>([]); const mcps = ref<Resource[]>([])
const loading = ref(false); const error = ref(''); const selectedKind = ref<'skill'|'mcp'>('skill')
const visibleResources = computed(() => (selectedKind.value === 'skill' ? skills.value : mcps.value).slice(0,3))
const communityEntries = [
  { to:'/forum', title:'参与讨论', description:'分享经验，交流想法，留下有价值的发现。', icon:MessagesSquare },
  { to:'/help-requests', title:'发布求助', description:'把需求说清楚，让合适的人与你相遇。', icon:CircleHelp },
  { to:'/collaborations', title:'推进协作', description:'跟进任务、记录决定，把成果交付到位。', icon:Handshake },
]
let controller: AbortController | undefined
async function load() { controller?.abort(); const request = new AbortController(); controller=request; loading.value=true; error.value=''; try { const [s,m] = await Promise.all([listResources({kind:'skill',q:'',scope:'all',page:0},request.signal),listResources({kind:'mcp',q:'',scope:'all',page:0},request.signal)]); if(request.signal.aborted)return; skills.value=s.items; mcps.value=m.items; skillTotal.value=s.total; mcpTotal.value=m.total } catch(e) {if(!request.signal.aborted)error.value=errorMessage(e)} finally{if(!request.signal.aborted)loading.value=false} }
function openResource(resource:Resource) { void router.push({path:resource.kind==='skill'?'/skills':'/mcp-servers',query:{resource:resource.id}}) }
onBeforeUnmount(()=>controller?.abort()); void load()
</script>
<style scoped>
.overview-main{max-width:1320px;margin:auto;padding:32px 36px 70px;}.overview-topline{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px;font:10px var(--nx-font-mono);letter-spacing:.1em;color:var(--nx-text-tertiary);}.overview-topline>span{display:flex;align-items:center;gap:8px;}.signal-dot{height:5px;width:5px;background:var(--nx-accent);box-shadow:0 0 10px var(--nx-accent);border-radius:50%;}.overview-hero{position:relative;overflow:hidden;display:grid;grid-template-columns:1.2fr 1fr;min-height:350px;padding:38px 40px;border:1px solid var(--nx-border-strong);border-radius:16px;background:var(--nx-hero-bg);}.hero-grid{position:absolute;inset:0;background-image:linear-gradient(var(--nx-grid) 1px,transparent 1px),linear-gradient(90deg,var(--nx-grid) 1px,transparent 1px);background-size:36px 36px;mask-image:linear-gradient(90deg,transparent,#000);pointer-events:none;}.hero-copy{position:relative;z-index:1;}.hero-kicker{font:10px var(--nx-font-mono);letter-spacing:.17em;color:var(--nx-accent);}.hero-copy h1{margin:18px 0;font-size:clamp(32px,3.9vw,52px);line-height:1.18;letter-spacing:-.055em;color:var(--nx-text-primary);font-weight:750;}.hero-copy em{font-style:normal;color:var(--nx-accent);}.hero-copy p{color:var(--nx-text-secondary);font-size:13px;line-height:1.9;}.hero-actions{display:flex;flex-wrap:wrap;gap:10px;margin-top:24px;}.network-art{position:relative;align-self:center;justify-self:center;width:280px;height:280px;}.orbit{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);border:1px solid var(--nx-accent-border);border-radius:50%;}.orbit-one{width:220px;height:220px;opacity:.65;}.orbit-two{width:280px;height:280px;border-style:dashed;opacity:.35;animation:orbit 100s linear infinite;}.orbit-three{width:145px;height:145px;opacity:.35;}.core-node{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;width:98px;height:98px;border:1px solid var(--nx-accent-border);border-radius:25px;background:var(--nx-bg-raised);color:var(--nx-accent);box-shadow:0 0 50px var(--nx-accent-subtle),inset 0 0 30px var(--nx-accent-subtle);}.core-node strong{font:9px var(--nx-font-mono);letter-spacing:.2em;}.satellite{position:absolute;display:flex;align-items:center;justify-content:center;gap:7px;padding:12px;border:1px solid var(--nx-border-strong);border-radius:10px;background:var(--nx-bg-overlay);box-shadow:var(--nx-shadow-menu);color:var(--nx-accent);}.satellite span{font:10px var(--nx-font-mono);}.satellite-a{top:24px;left:2px;}.satellite-b{right:-10px;bottom:56px;color:var(--nx-secondary);}.satellite-c{bottom:14px;left:46px;}.art-caption{position:absolute;bottom:-25px;width:100%;text-align:center;font:8px var(--nx-font-mono);letter-spacing:.16em;color:var(--nx-text-tertiary);}@keyframes orbit{to{transform:translate(-50%,-50%) rotate(360deg)}}
.overview-stats{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-top:16px;}.overview-stats a{display:flex;align-items:center;gap:12px;padding:20px;border:1px solid var(--nx-border-default);border-radius:10px;background:var(--nx-bg-raised);color:var(--nx-accent);}.overview-stats a:hover{border-color:var(--nx-accent-border);}.overview-stats span{font-size:12px;color:var(--nx-text-primary);}.overview-stats small{display:block;color:var(--nx-text-tertiary);font-size:10px;margin-top:5px;}.overview-stats strong{margin-left:auto;font:26px var(--nx-font-mono);color:var(--nx-text-primary);}.overview-stats a>svg:last-child{margin-left:auto;color:var(--nx-text-tertiary);}.discovery-section,.community-section{margin-top:36px;}.section-heading{display:flex;align-items:center;gap:22px;margin-bottom:20px;}.section-index{font:9px var(--nx-font-mono);letter-spacing:.12em;color:var(--nx-text-tertiary);}.section-heading h2{font-size:20px;letter-spacing:-.03em;color:var(--nx-text-primary);margin-top:7px;}.section-heading>a{display:flex;align-items:center;gap:4px;margin-left:auto;font-size:12px;color:var(--nx-text-tertiary);}.discovery-tabs{display:flex;background:var(--nx-bg-inset);border:1px solid var(--nx-border-default);border-radius:8px;padding:3px;margin-top:12px;}.discovery-tabs button{height:30px;padding:0 15px;border:0;border-radius:5px;background:transparent;font-size:11px;color:var(--nx-text-tertiary);}.discovery-tabs .active{background:var(--nx-bg-active);color:var(--nx-accent);}.community-entry-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px;}.community-entry{display:flex;align-items:flex-start;gap:13px;padding:22px;border:1px solid var(--nx-border-default);border-radius:12px;background:var(--nx-bg-raised);}.entry-icon{color:var(--nx-accent);padding-top:3px;}.community-entry h3{color:var(--nx-text-primary);font-size:15px;margin-bottom:8px;}.community-entry p{font-size:12px;line-height:1.8;color:var(--nx-text-tertiary);}.community-entry>svg{flex-shrink:0;margin-left:auto;color:var(--nx-text-tertiary);}.community-entry:hover{border-color:var(--nx-accent-border);}.overview-footer{display:flex;justify-content:space-between;gap:16px;border-top:1px solid var(--nx-border-default);margin-top:36px;padding-top:22px;color:var(--nx-text-tertiary);font:9px var(--nx-font-mono);}.overview-footer a{display:flex;gap:5px;align-items:center;font-size:11px;}
@media(max-width:1100px){.overview-hero{padding:30px;}.network-art{transform:scale(.8);}.overview-stats{gap:10px;}.overview-stats a{padding:16px;}.overview-stats small{display:none;}.community-entry-grid{grid-template-columns:1fr;}.community-entry{align-items:center;}.community-entry p{margin:0;}.community-entry h3{margin-bottom:4px;}}
@media(max-width:720px){.overview-main{padding:24px 16px 100px;}.overview-topline{font-size:8px;}.overview-hero{grid-template-columns:1fr;padding:26px;min-height:auto;}.network-art{display:none;}.hero-copy h1{font-size:38px;}.hero-grid{mask-image:none;opacity:.5;}.hero-copy p{font-size:12px;}.hero-actions{gap:8px;}.hero-actions .btn{padding:0 12px;font-size:12px;}.overview-stats{grid-template-columns:1fr 1fr;gap:10px;}.overview-stats a{padding:14px 12px;gap:8px;}.overview-stats a:last-child{grid-column:1 / -1;}.overview-stats strong{font-size:22px;}.overview-stats a>svg:last-child{display:none;}.overview-stats small{display:block;font-size:9px;}.overview-stats a>svg:first-child{width:16px;}.section-heading{gap:12px;flex-wrap:wrap;}.section-heading h2{font-size:18px;}.discovery-tabs{margin:0 0 0 auto;}.section-heading>a{margin-left:0;font-size:11px;}.discovery-tabs button{padding:0 10px;}.overview-footer{flex-direction:column;}.overview-stats span{font-size:11px;}}
</style>
